CREATE TABLE BUDGET_USE(
	ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	USE_CODE INTEGER,
	EXPENSE INTEGER
);

INSERT INTO BUDGET_USE(USE_CODE, EXPENSE) VALUES (1, 1000000);
INSERT INTO BUDGET_USE(USE_CODE, EXPENSE) VALUES (2, 50000);
INSERT INTO BUDGET_USE(USE_CODE, EXPENSE) VALUES (1, 1200000);
INSERT INTO BUDGET_USE(USE_CODE, EXPENSE) VALUES (1, 2000000);
INSERT INTO BUDGET_USE(USE_CODE, EXPENSE) VALUES (2, 230000);
INSERT INTO BUDGET_USE(USE_CODE, EXPENSE) VALUES (2, 150000);
INSERT INTO BUDGET_USE(USE_CODE, EXPENSE) VALUES (1, 800000);
INSERT INTO BUDGET_USE(USE_CODE, EXPENSE) VALUES (1, 2000000);
INSERT INTO BUDGET_USE(USE_CODE, EXPENSE) VALUES (1, 1000000);