CREATE TABLE GYM_MEMBER(
	MEMBER_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	SQUAT INTEGER,
	BENCH_PRESS INTEGER,
	DEADLIFT INTEGER
) AUTO_INCREMENT = 1;

INSERT INTO GYM_MEMBER(SQUAT, BENCH_PRESS, DEADLIFT) VALUES(110, 90, 80);
INSERT INTO GYM_MEMBER(SQUAT, BENCH_PRESS, DEADLIFT) VALUES(40, 40, 20);
INSERT INTO GYM_MEMBER(SQUAT, BENCH_PRESS, DEADLIFT) VALUES(250, 250, 180);
INSERT INTO GYM_MEMBER(SQUAT, BENCH_PRESS, DEADLIFT) VALUES(330, 210, 140);
INSERT INTO GYM_MEMBER(SQUAT, BENCH_PRESS, DEADLIFT) VALUES(5, 5, 5);
INSERT INTO GYM_MEMBER(SQUAT, BENCH_PRESS, DEADLIFT) VALUES(330, 350, 310);