CREATE TABLE STUDENT(
	ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	MATH INTEGER,
	PHYSICS INTEGER,
	CHEMISTRY INTEGER
);

INSERT INTO STUDENT(MATH, PHYSICS, CHEMISTRY) VALUES(100, 50, 50);
INSERT INTO STUDENT(MATH, PHYSICS, CHEMISTRY) VALUES(57, 32, 47);
INSERT INTO STUDENT(MATH, PHYSICS, CHEMISTRY) VALUES(88, 39, 41);
INSERT INTO STUDENT(MATH, PHYSICS, CHEMISTRY) VALUES(92, 44, 31);
INSERT INTO STUDENT(MATH, PHYSICS, CHEMISTRY) VALUES(17, 50, 50);
INSERT INTO STUDENT(MATH, PHYSICS, CHEMISTRY) VALUES(100, 8, 7);
INSERT INTO STUDENT(MATH, PHYSICS, CHEMISTRY) VALUES(77, 45, 45);
INSERT INTO STUDENT(MATH, PHYSICS, CHEMISTRY) VALUES(69, 36, 46);
INSERT INTO STUDENT(MATH, PHYSICS, CHEMISTRY) VALUES(81, 47, 40);
INSERT INTO STUDENT(MATH, PHYSICS, CHEMISTRY) VALUES(66, 36, 35);